name: Sonarqube scan for master branch

on:
  workflow_dispatch:

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup sonar scanner
        uses: warchant/setup-sonar-scanner@v3

      - name: 'Checkout repository on branch: ${{ github.REF }}'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.REF }}
          fetch-depth: 0

      - name: Sonarscanner for dotnet
        uses: Secbyte/dotnet-sonarscanner@v2.3
        with:
          buildCommand: dotnet build .
          projectKey: arl-sdk
          projectName: arl-sdk
          sonarOrganisation: default-organization
          sonarHostname: https://sonarqube.svc.platform.myobdev.com/
          beginArguments: >
              /d:sonar.verbose="true"
              /d:sonar.cs.opencover.reportsPaths='"/path/to/coverage.xml","/path/to/coverage.2.xml"'
              /d:sonar.coverage.exclusions='"**/*.cs","**/*.md"'
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
